---
name: Lint commit messages
on: [pull_request]
jobs:
  lint-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install modules
        run: npm install

      - name: Lint commit message
        run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
