---
name: Lint commit messages
on: [pull-request]
jobs:
  lint-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: npm install

      - name: Lint commit message
        run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
