---
name: Unit tests
on: [push]
jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: npm install

      - name: Compile
        run: npm run build

      - name: Run tests
        run: npm test
