---
name: Unit tests
on: [push]
jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"

      - name: Install modules
        run: npm install

      - name: Run tests
        run: npm test
